# -*- coding: utf-8 -*-
"""Bingo.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hgbDuj56GhVOBubsrcpqybAfporPIlRX
"""

from unidecode import unidecode

def solicita_entrada(catalogo, entrada):
  while True:
    nome = input(entrada).title()
    nome = unidecode(nome)
    try:
      catalogo[nome]
      break
    except KeyError:
      print("Por favor, digite uma entrada válida")

  return nome

######################################################################################################

def bingo_futebol(catalogoJogadores, catalogoTimes):
  jgrRestantes = len(catalogoJogadores)
  timesRestantes = 20
  skips = 3

  while timesRestantes > 0 and skips >= 0:

    ###########################################
    # MENSAGEM NA RETA FINAL
    ###########################################

    if timesRestantes <= 5:
      conjJogadores = set([])
      for time in catalogoTimes:
        conjJogadores = conjJogadores | set(catalogoTimes[time])

      jgrUteis = len(conjJogadores)
      chance = (jgrUteis/jgrRestantes)*100

      print("Quase lá! Só falta(m)", timesRestantes, "time(s)!!")
      print('Restam', jgrRestantes, 'possibilidades de jogadores a serem sorteados, dos quais', jgrUteis, 'são "úteis"!')
      print("Isso significa uma chance de ", format(chance, '.2f'), "% de sucesso para o próximo sorteio!\n", sep="")

    ###########################################
    # SOLICITA O JOGADOR
    ###########################################

    jgrSorteado = solicita_entrada(catalogoJogadores, "Digite o jogador sorteado pelo filtro: ")
    print("")

    timesJogados = sorted(catalogoJogadores[jgrSorteado]) #Lista com os times que o jogador atuou
    qntTimes = len(timesJogados) #Quantidade de times que o jogador atuou

    ###########################################
    # IF PARA AVALIAR CASO A CASO
    ###########################################

    #Caso de skip:
    if qntTimes == 0:
      skips += -1
      print("Não há times disponíveis para esse jogador. Você deve usar um pulo.")
      print("Pulos restantes:", skips)
      timeEscolhido = "Skip"

    #Caso em que só há um time disponível:
    elif qntTimes == 1:
      timeEscolhido = timesJogados[0]
      print("Só há um time disponível para esse jogador:", timeEscolhido)
      catalogoTimes[timeEscolhido].remove(jgrSorteado) #Remove o jogador das opções daquele único time

    #Caso em que há mais de um time disponível:
    else:
      #Imprime os times que o jogador já atuou:
      print(jgrSorteado, "jogou pelos seguintes times disponíveis:", end=" ")
      for i in range(qntTimes):
        print(timesJogados[i], end="; ")

      #Remove o jogador das opções de cada time que ele já atuou:
      for time in timesJogados:
        catalogoTimes[time].remove(jgrSorteado)

      #Define a quantidade de jogadores "exclusivos" e "gerais" dos "times candidatos":
      lstExclusivos = []
      lstGerais = []
      for time in timesJogados:
        qntGeral = len(catalogoTimes[time]) #Verifica a quantidade de jogadores disponíveis, em geral, para o time em questão
        jgrExcl = 0 #Inicia a variável para jogadores exclusivos
        for jogador in catalogoTimes[time]: #Acessa cada jogador de cada time do atleta sorteado
          timesJogador = len(catalogoJogadores[jogador]) #Verifica em quantos times disponíveis esse jogador atuou
          if timesJogador == 1:
            jgrExcl += 1
        lstExclusivos.append([jgrExcl, time])
        lstGerais.append([qntGeral, time])

      lstExclusivos = sorted(lstExclusivos)
      lstGerais = sorted(lstGerais)

      #Imprime os jogadores exclusivos:
      print('\nA quantidade de "jogadores exclusivos" restantes em cada time é:\n')
      for i in range(len(lstExclusivos)):
        print(lstExclusivos[i][1], "=", lstExclusivos[i][0])

      #Imprime os jogadores gerais:
      print('\nA quantidade de "jogadores gerais" restantes em cada time é:\n')
      for i in range(len(lstGerais)):
        print(lstGerais[i][1], "=", lstGerais[i][0])

      #Solicita a resposta do usuário:
      timeEscolhido = solicita_entrada(catalogoTimes, "\nDigite o time a ser marcado: ")

    ###########################################
    # TRABALHA COM O TIME ESCOLHIDO/SKIP
    ###########################################

    #Verifica se um time foi escolhido ou se houve um pulo forçado:
    if timeEscolhido != "Skip":
      #Remove o time escolhido do registro dos jogadores que atuaram nele:
      for jogador in catalogoTimes[timeEscolhido]:
        catalogoJogadores[jogador].remove(timeEscolhido)
      #Remove o time escolhido do catálogo de times:
      catalogoTimes.pop(timeEscolhido)
      timesRestantes += -1

    catalogoJogadores.pop(jgrSorteado)
    jgrRestantes += -1
    print("")

  ###########################################
  # MENSAGEM AO FIM DO JOGO
  ###########################################

  if timesRestantes == 0:
    print("\nBINGO!!!!!!")
  else:
    print("Você perdeu!")
    print("Não há opção disponível para esse jogador e seus pulos acabaram.")

catalogoJogadores = {
    "Piquerez": ["Palmeiras"],
    "Endrick": ["Palmeiras"],
    "Gomez": ["Palmeiras"],
    "Dudu": ["Coritiba", "Cruzeiro", "Gremio", "Palmeiras"],
    "Veiga": ["Athletico", "Coritiba", "Palmeiras"],
    "Roger Guedes": ["Atletico", "Corinthians", "Palmeiras"],
    "Diego Souza": ["Fluminense", "Flamengo", "Gremio", "Palmeiras", "Atletico", "Vasco", "Cruzeiro", "Sao Paulo", "Botafogo"],
    "Ganso": ["Fluminense", "Santos", "Sao Paulo"],
    "Marcelo": ["Fluminense"],
    "Felipe Melo": ["Flamengo", "Cruzeiro", "Gremio", "Palmeiras", "Fluminense"],
    "Guga": ["Atletico", "Fluminense"],
    "Bigode": ["Athletico", "Corinthians", "Cruzeiro", "Fluminense", "Palmeiras"],
    "Cano": ["Fluminense", "Vasco"],
    "Alemao": ["Internacional"],
    "Wanderson": ["Internacional"],
    "Luiz Adriano": ["Internacional", "Palmeiras"],
    "Wellington Paulista": ["Santos", "Botafogo", "Cruzeiro", "Palmeiras", "Internacional", "Coritiba", "Fluminense", "Fortaleza", "America"],
    "Galhardo": ["Botafogo", "Coritiba", "Vasco", "Internacional", "Fortaleza"],
    "John": ["Santos", "Internacional"],
    "David Luiz": ["Flamengo"],
    "Leo Pereira": ["Athletico", "Flamengo"],
    "Varella": ["Flamengo"],
    "Gabigol": ["Flamengo", "Santos"],
    "Pedro": ["Flamengo", "Fluminense"],
    "Arrascaeta": ["Cruzeiro", "Flamengo"],
    "Fernandinho": ["Athletico"],
    "Terans": ["Athletico", "Atletico"],
    "Vitor Bueno": ["Athletico", "Santos", "Sao Paulo"],
    "Pablo": ["Athletico", "Sao Paulo"],
    "Vitor Roque": ["Athletico", "Cruzeiro"],
    "Cuesta": ["Botafogo", "Internacional"],
    "Tiquinho": ["Botafogo"],
    "Pedro Raul": ["Botafogo", "Goias", "Vasco"],
    "Perri": ["Botafogo", "Sao Paulo"],
    "Pacheco": ["Fortaleza", "Bragantino"],
    "Robson": ["Coritiba", "Fortaleza", "Sao Paulo"],
    "Fernando Miguel": ["Gremio", "Vasco", "Fortaleza"],
    "Pikachu": ["Fortaleza", "Vasco"],
    "Bruninho": ["Bragantino"],
    "Raul": ["Bragantino","Vasco"],
    "Alerrandro": ["Atletico", "Bragantino"],
    "Helinho": ["Bragantino", "Sao Paulo"],
    "Natan": ["Bragantino", "Flamengo"],
    "Sasha": ["Internacional", "Bragantino", "Goias", "Santos", "Atletico"],
    "Avelar": ["America", "Corinthians"],
    "Aloisio": ["Gremio", "Sao Paulo", "America"],
    "Calleri": ["Sao Paulo"],
    "Reinaldo": ["Gremio", "Sao Paulo"],
    "Suarez": ["Gremio"],
    "Kannemann": ["Gremio"],
    "Apodi": ["Cruzeiro", "Santos", "Goias", "Bahia"],
    "Tadeu": ["Coritiba", "Goias"],
    "Soteldo": ["Santos"],
    "Joao Paulo": ["Santos"],
    "Liziero": ["Coritiba", "Internacional", "Sao Paulo"],
    "Rafinha": ["Coritiba", "Flamengo", "Sao Paulo", "Gremio"],
    "Pitta": ["Cuiaba"],
    "Deyverson": ["Palmeiras", "Cuiaba"],
    "Sobral": ["Cuiaba"],
    "Walter": ["Corinthians", "Cuiaba"],
    "Jair": ["Atletico", "Vasco", "Internacional"],
    "Pumita": ["Vasco"],
    "Kanu": ["Botafogo", "Bahia"],
    "Raul Gustavo": ["Bahia", "Corinthians"],
    "Danilo Fernandes": ["Corinthians", "Bahia", "Internacional"],
    "Ademir": ["America", "Atletico", "Bahia"],
    "Rafael Cabral": ["Cruzeiro", "Santos"],
    "Hulk": ["Atletico"],
    "Renato Augusto": ["Corinthians", "Flamengo"],
    "Cassio": ["Corinthians", "Gremio"],
    "Vagner Love": ["Corinthians", "Flamengo", "Palmeiras"],
    "Rony": ["Athletico", "Cruzeiro", "Palmeiras"],
    "Henrique Dourado": ["Santos", "Flamengo", "Palmeiras", "Cruzeiro", "Fluminense"],
    "Guerrero": ["Corinthians", "Flamengo", "Internacional"],
    "Benitez": ["Vasco", "Sao Paulo", "Gremio", "America"],
    "Maicon": ["Cruzeiro", "Sao Paulo", "Vasco", "Santos"],
    "Zanocelo": ["Santos", "Fortaleza"],
    "Pedro Henrique": ["Corinthians", "Athletico", "Bragantino"]
}

catalogoTimes = {
    "America": ["Benitez", "Wellington Paulista", "Avelar", "Aloisio", "Ademir"],
    "Athletico": ["Pedro Henrique", "Rony", "Pablo", "Veiga", "Bigode", "Leo Pereira", "Fernandinho", "Terans", "Vitor Bueno", "Vitor Roque"],
    "Atletico": ["Hulk", "Roger Guedes", "Diego Souza", "Guga", "Terans", "Alerrandro", "Sasha", "Jair", "Ademir"],
    "Bahia": ["Apodi", "Kanu", "Raul Gustavo", "Danilo Fernandes", "Ademir"],
    "Botafogo": ["Kanu", "Diego Souza", "Wellington Paulista", "Galhardo", "Cuesta", "Tiquinho", "Pedro Raul", "Perri"],
    "Bragantino": ["Pedro Henrique", "Pacheco", "Raul", "Bruninho", "Alerrandro", "Helinho", "Natan", "Sasha"],
    "Corinthians": ["Pedro Henrique", "Guerrero", "Vagner Love", "Cassio", "Renato Augusto", "Roger Guedes", "Bigode", "Avelar", "Walter", "Raul Gustavo", "Danilo Fernandes"],
    "Coritiba": ["Rafinha", "Dudu", "Veiga", "Wellington Paulista", "Galhardo", "Robson", "Tadeu", "Liziero"],
    "Cruzeiro": ["Maicon", "Henrique Dourado", "Rony", "Rafael Cabral", "Dudu", "Diego Souza", "Felipe Melo", "Bigode", "Wellington Paulista", "Arrascaeta", "Vitor Roque", "Apodi"],
    "Cuiaba": ["Deyverson", "Pitta", "Sobral", "Walter"],
    "Flamengo": ["Guerrero", "Henrique Dourado", "Vagner Love", "Renato Augusto", "Rafinha", "Diego Souza", "Felipe Melo", "David Luiz", "Varella", "Leo Pereira", "Gabigol", "Pedro", "Arrascaeta", "Natan"],
    "Fluminense": ["Henrique Dourado", "Pedro", "Diego Souza", "Ganso", "Marcelo", "Felipe Melo", "Guga", "Bigode", "Cano", "Wellington Paulista"],
    "Fortaleza": ["Zanocelo", "Wellington Paulista", "Galhardo", "Pacheco", "Robson", "Fernando Miguel", "Pikachu"],
    "Goias": ["Pedro Raul", "Sasha", "Apodi", "Tadeu"],
    "Gremio": ["Benitez", "Cassio", "Rafinha", "Aloisio", "Dudu", "Diego Souza", "Felipe Melo", "Fernando Miguel", "Reinaldo", "Suarez", "Kannemann"],
    "Internacional": ["Guerrero", "Danilo Fernandes", "Jair", "Liziero", "Sasha", "John", "Galhardo", "Alemao", "Wanderson", "Luiz Adriano", "Wellington Paulista", "Cuesta"],
    "Palmeiras": ["Henrique Dourado", "Rony", "Vagner Love", "Deyverson", "Piquerez", "Endrick", "Gomez", "Dudu", "Veiga", "Roger Guedes", "Diego Souza", "Felipe Melo", "Bigode", "Luiz Adriano", "Wellington Paulista"],
    "Santos": ["Zanocelo", "Maicon", "Henrique Dourado", "Rafael Cabral", "Vitor Bueno", "Ganso", "Wellington Paulista", "John", "Gabigol", "Sasha", "Apodi", "Soteldo", "Joao Paulo"],
    "Sao Paulo": ["Maicon", "Benitez", "Rafinha", "Aloisio", "Vitor Bueno", "Diego Souza", "Ganso", "Pablo", "Perri", "Robson", "Helinho", "Calleri", "Reinaldo", "Liziero"],
    "Vasco": ["Maicon", "Benitez", "Diego Souza", "Cano", "Galhardo", "Pedro Raul", "Fernando Miguel", "Pikachu", "Raul", "Jair", "Pumita"]
}

bingo_futebol(catalogoJogadores, catalogoTimes)